import { priceForQuantity, groupBookingError } from './rules.js';
export function initializeWebsite(root = document) {
 const controller = new AbortController(); const signal = controller.signal;
 const on=(el,event,fn)=>el?.addEventListener(event,fn,{signal});
 const all=s=>Array.from(root.querySelectorAll(s)); const one=s=>root.querySelector(s);
 let quantity=1; const cart=new Map();
 function toast(message) { const el=one('#notice'); if(!el)return; el.textContent=message;el.classList.add('show');window.clearTimeout(el.hideTimer);el.hideTimer=window.setTimeout(()=>el.classList.remove('show'),3500); }
 function setQuantity(next){quantity=Math.max(1,Math.floor(next));all('[data-quantity]').forEach(el=>el.textContent=quantity+' KG');all('[data-price]').forEach(el=>el.textContent='₹'+priceForQuantity(quantity)); const input=one('#order-quantity');if(input)input.value=quantity;}
 all('[data-qty]').forEach(el=>on(el,'click',()=>setQuantity(quantity+Number(el.dataset.qty))));
 function renderCart(){let total=0,count=0;const list=one('#cart-items'); if(!list)return;list.replaceChildren();cart.forEach((item,key)=>{count+=item.quantity;if(item.priced)total+=priceForQuantity(item.quantity);const row=document.createElement('div');row.className='cart-row'; const detail=document.createElement('div'); const name=document.createElement('strong'); name.textContent=key; const info=document.createElement('small');info.textContent=item.priced?`${item.quantity} KG · ₹${priceForQuantity(item.quantity)}`:`${item.quantity} serving(s) · Ask for Price`;detail.append(name,info);const remove=document.createElement('button');remove.className='icon-btn';remove.type='button';remove.setAttribute('aria-label',`Remove ${key}`);remove.innerHTML='<i class="bi bi-trash3"></i>';on(remove,'click',()=>{cart.delete(key);renderCart();});row.append(detail,remove);list.append(row);}); if(!cart.size)list.innerHTML='<p class="muted">Your next hill-station treat starts here.</p>';all('[data-cart-count]').forEach(el=>el.textContent=String(count));one('#cart-total').textContent='₹'+total+(Array.from(cart.values()).some(i=>!i.priced)?' + unpriced snacks':'');one('#place-order').disabled=!cart.size;}
 function add(name,priced=false){const old=cart.get(name);cart.set(name,{quantity:(old?.quantity||0)+(priced?quantity:1),priced});renderCart();toast('Added to your order!');all('[data-cart-count]').forEach(el=>{el.classList.remove('pop');void el.offsetWidth;el.classList.add('pop');});}
 all('[data-add]').forEach(el=>on(el,'click',()=>{add(el.dataset.add,el.dataset.priced==='true');if(el.dataset.buy==='true')one('#cart-dialog').showModal();}));
 all('[data-cart-open]').forEach(el=>on(el,'click',()=>one('#cart-dialog').showModal()));
 all('[data-dialog-close]').forEach(el=>on(el,'click',()=>el.closest('dialog').close()));
 all('dialog').forEach(el=>on(el,'click',e=>{if(e.target===el){const r=el.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)el.close();}}));
 all('[data-filter]').forEach(el=>on(el,'click',()=>{all('[data-filter]').forEach(b=>{b.classList.toggle('active',b===el);b.setAttribute('aria-pressed',String(b===el));});all('[data-category]').forEach(card=>card.hidden=el.dataset.filter!=='All'&&card.dataset.category!==el.dataset.filter);}));
 on(one('#mobile-toggle'),'click',()=>{const expanded=one('#site-nav').classList.toggle('is-open');one('#mobile-toggle').setAttribute('aria-expanded',String(expanded));});
 all('a[href^="#"]').forEach(el=>on(el,'click',()=>{one('#site-nav').classList.remove('is-open');one('#mobile-toggle').setAttribute('aria-expanded','false');}));
 const scroll=()=>{one('#site-header')?.classList.toggle('scrolled',window.scrollY>30);one('#back-top')?.classList.toggle('visible',window.scrollY>700);};on(window,'scroll',scroll);scroll();on(one('#back-top'),'click',()=>window.scrollTo({top:0,behavior:'smooth'}));
 on(one('#place-order'),'click',()=>{one('#cart-dialog').close();one('#order-summary').textContent=Array.from(cart.entries()).map(([name,item])=>`${name} × ${item.quantity}${item.priced?' KG':''}`).join(' • ');one('#order-dialog').showModal();});
 on(one('#delivery'),'change',e=>{one('#address').required=e.target.value==='Delivery';one('#address-label').textContent=e.target.value==='Delivery'?'Delivery address *':'Address (optional for pickup)';});
 function download(data,file){const url=URL.createObjectURL(new Blob([data],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=file;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 on(one('#order-form'),'submit',e=>{e.preventDefault();const form=e.target;if(!form.reportValidity())return;const data=new FormData(form);const kg=Math.max(1,Number(data.get('Quantity'))||1);if(cart.has('Mudavattu Kilangu')){cart.set('Mudavattu Kilangu',{quantity:kg,priced:true});renderCart();}download('MP Snacks & Bites — Order request (not yet sent)\n'+Array.from(cart.entries()).map(([name,i])=>`${name}: ${i.quantity}${i.priced?' KG — ₹'+priceForQuantity(i.quantity):' serving(s) — price to confirm'}`).join('\n')+'\n\n'+Array.from(data.entries()).map(([k,v])=>`${k}: ${v}`).join('\n'),'mp-snacks-order.txt');one('#order-status').textContent='Your request has been downloaded, not sent. Please share it with the café in person to confirm availability and delivery.';});
 all('[data-group-open]').forEach(el=>on(el,'click',()=>one('#group-dialog').showModal()));
 on(one('#group-form'),'submit',e=>{e.preventDefault();const form=e.target;const error=groupBookingError(one('#group-people').value);one('#group-error').textContent=error;if(error||!form.reportValidity())return;download('MP Snacks & Bites — Group request (not yet sent)\n'+Array.from(new FormData(form).entries()).map(([k,v])=>`${k}: ${v}`).join('\n'),'mp-snacks-group-request.txt');one('#group-status').textContent='Your group request has been downloaded, not sent. Share it with the café in person to confirm your booking.';});
 on(one('#group-people'),'input',()=>{one('#group-error').textContent=groupBookingError(one('#group-people').value);});
 all('[data-contact-missing]').forEach(el=>on(el,'click',()=>toast('Contact details will be added soon. Please visit us at Waterfront Hotel, Yercaud.')));
 const date=one('#group-date');if(date){const d=new Date();date.min=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');}
 renderCart();setQuantity(1);return ()=>{controller.abort();all('dialog').forEach(el=>el.close());};
}
if (typeof document !== 'undefined' && document.documentElement.dataset.standalone === 'true') initializeWebsite();
